let cyan_print = ANSITerminal.print_string [ ANSITerminal.cyan ]
let magenta_print = ANSITerminal.print_string [ ANSITerminal.magenta ]
let red_print = ANSITerminal.print_string [ ANSITerminal.red ]
let green_print = ANSITerminal.print_string [ ANSITerminal.green ]
let yellow_print = ANSITerminal.print_string [ ANSITerminal.yellow ]